# Question 3

Using the diabetes data of Table 3.5, do the following:

In [2]:
data <- read.table(file = "/Users/alexwiigs/Documents/Code/STAT 553 Textbook/T3_5_DIABETES.DAT")
data <- data[, -1]
colnames(data) <- c("y1","y2","x1","x2","x3")
t(data)

[,1]   [,2]   [,3]   [,4]   [,5] [,6]   [,7]   [,8]  [,9]   [,10]  [,11]
y1   0.81   0.95   0.94   1.04   1    0.76   0.91   1.1   0.99   0.78 ...  
y2  80.00  97.00 105.00  90.00  90   86.00 100.00  85.0  97.00  97.00 ...  
x1 356.00 289.00 319.00 356.00 323  381.00 350.00 301.0 379.00 296.00 ...  
x2 124.00 117.00 143.00 199.00 240  157.00 221.00 186.0 142.00 131.00 ...  
x3  55.00  76.00 105.00 108.00 143  165.00 119.00 105.0  98.00  94.00 ...  
   [,12]  [,13]  [,14]  [,15] [,16] [,17]  [,18]  [,19]  [,20]  [,21] 
y1   1.17   0.85   0.97   1     1     0.89   0.98   0.78   0.74   0.91
y2 100.00  78.00 106.00  98   102    90.00  94.00  80.00  93.00  86.00
x1 367.00 335.00 396.00 277   378   360.00 291.00 269.00 318.00 328.00
x2 182.00 241.00 128.00 222   165   282.00  94.00 121.00  73.00 106.00
x3  54.00 175.00  80.00 186   117   160.00  71.00  29.00  42.00  56.00

In [3]:
info <- as.matrix(c(46,2,3))
rownames(info) <- c("n","p","q")
t(info)

n  p q
[1,] 46 2 3

**a)** Find the least squares estimate for the regression of $(y_1,y_2)$ on $(x_1,x_2,x_3)$. Write out the fitted models for $y_1$ and $y_2$.

First we must create the $\textbf{X}$ matrix and $\textbf{y}$ vector.

In [4]:
# X matrix
Xblock <- function(i) {
    row1 <- as.numeric( unname( cbind( matrix(1), data[i, 3:5], matrix(0, ncol = info["q",] + 1)    ) ) )
    row2 <- as.numeric( unname( cbind( matrix(0, ncol = (info["q",] + 1) ), matrix(1), data[i, 3:5] ) ) )
    return(rbind(row1,row2))}

X <- Xblock(1)
for (i in 2:info["n",]) {X <- unname( rbind(X, Xblock(i) ) ) }
dim(X)
t(X)

[1] 92  8

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]   1    0    1    0    1    0    1    0    1    0   ...     1     0     1  
[2,] 356    0  289    0  319    0  356    0  323    0   ...   360     0   291  
[3,] 124    0  117    0  143    0  199    0  240    0   ...   282     0    94  
[4,]  55    0   76    0  105    0  108    0  143    0   ...   160     0    71  
[5,]   0    1    0    1    0    1    0    1    0    1   ...     0     1     0  
[6,]   0  356    0  289    0  319    0  356    0  323   ...     0   360     0  
[7,]   0  124    0  117    0  143    0  199    0  240   ...     0   282     0  
[8,]   0   55    0   76    0  105    0  108    0  143   ...     0   160     0  
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,]   0     1     0     1     0     1     0  
[2,]   0   269     0   318     0   328     0  
[3,]   0   121     0    73     0   106     0  
[4,]   0    29     0    42     0    56     0  
[5,]   1     0     1     0     1     0     1  
[6,] 291     0   269     0   318     0   328  
[7,]  94     0   121     0    73     0   106  
[8,]  71     0    29     0    42     0    56

In [11]:
# y vector
yblock <- function(i) {block = rbind(data[i,"y1"],data[i,"y2"])}

y <- yblock(1)
for (i in 2:info["n",]) { y <- rbind(y, yblock(i)) }
dim(y)

[1] 92  1

The LSE for the regression is: 
$$ \hat{\beta}_{LS} = ( \textbf{X}' \textbf{X} )^{-1} \textbf{X}' \textbf{y}$$

We calculate the coefficients to be...

In [6]:
B <- matrix(solve( t(X) %*% X ) %*% t(X) %*% y)
round(t(B),4)

[,1]   [,2]  [,3]   [,4]   [,5]    [,6]   [,7]    [,8]   
[1,] 0.6264 9e-04 -0.001 0.0015 83.2425 0.0287 -0.0127 -0.0044

**b)** Compute the estimate of $\Sigma$, the covariance matrix of $y_1$ and $y_2$.   

We have:
$$ \hat{\textbf{y}} = x \hat \beta_{LS} = \begin{pmatrix} \hat{\textbf{y}}_1 \\ \vdots \\ \hat{\textbf{y}}_n \end{pmatrix}$$
$$\textbf{y} - \hat{\textbf{y}} = \begin{pmatrix}\textbf{y}_1 - \hat{\textbf{y}}_1 \\ \vdots \\\textbf{y}_n - \hat{\textbf{y}}_n \end{pmatrix} = \begin{pmatrix} \textbf{e}_1 \\ \vdots \\ \textbf{e}_n \end{pmatrix} $$
So we compute $\hat \Sigma$ as:
$$\hat \Sigma = \frac{\sum_{i=1}^n \textbf{e}_i \textbf{e}_i'}{n-q-1}$$

In [12]:
# Calculate estimated covariance matrix of y1,y2
Epsilon <- (rbind(data[1,1], data[1,2]) - Xblock(1) %*% B) %*% t(rbind(data[1,1], data[1,2]) - Xblock(1) %*% B)
for (i in 2:info["n",]) { Epsilon <- Epsilon + (rbind(data[i,1], data[i,2]) - Xblock(i) %*% B) %*% t(rbind(data[i,1], data[i,2]) - Xblock(i) %*% B) }
Epsilon <- Epsilon / 42
unname(Epsilon)

[,1]       [,2]      
[1,] 0.01285864  0.2146721
[2,] 0.21467207 74.3673179

**c)** Using the estimate of $\Sigma$ in part b), find the estimated standard errors of the least squares estimates in a).

The standard error for $y_1 = \sqrt{\Sigma_{11}}$

In [8]:
round(sqrt(Epsilon[1,1]),4)

[1] 0.1134

The standard error for $y_2 = \sqrt{\Sigma_{22}}$

In [9]:
round(sqrt(Epsilon[2,2]),4)

[1] 8.6236

**Double Check Calculations using lm plugin:**

In [10]:
mlr <- lm( cbind(data[,1], data[,2]) ~ x1 + x2 + x3, data)
summary(mlr)

Response data[, 1] :

Call:
lm(formula = `data[, 1]` ~ x1 + x2 + x3, data = data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.308182 -0.073001  0.006621  0.048729  0.303786 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.6263903  0.1757270   3.565 0.000925 ***
x1           0.0009082  0.0005252   1.729 0.091077 .  
x2          -0.0009557  0.0004141  -2.308 0.025993 *  
x3           0.0014897  0.0004250   3.505 0.001100 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1134 on 42 degrees of freedom
Multiple R-squared:  0.2583,	Adjusted R-squared:  0.2054 
F-statistic: 4.877 on 3 and 42 DF,  p-value: 0.005341


Response data[, 2] :

Call:
lm(formula = `data[, 2]` ~ x1 + x2 + x3, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.4731  -4.7612   0.5168   7.2208  14.8842 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 83.24254

Values match lm output, as expected.