# Question 4
## a)
We have $ \textbf{y} \sim N_4( \mu, \Sigma)$ and $\textbf{z} \sim N_4(0,I_4)$, where
$$\mu = \begin{pmatrix} 1 \\ 3 \\ 5 \\ 6 \end{pmatrix}$$
and 
$$\Sigma = \begin{pmatrix} 14 & 12 & 1 & 8 \\ 12 & 14 & 5 & 1 \\ 1 & 5 & 6 & -7 \\ 8 & 1 & -7 & 27 \end{pmatrix}$$


In [9]:
Sigma <- matrix(c(14,12,1,8,12,14,5,1,1,5,6,-7,8,1,-7,27), ncol = 4)
mu <- matrix(c(1,3,5,6))

First notice that $(\textbf{y} - \mu) \sim N_4(0, \Sigma) \implies (\Sigma^{1/2})^{-1}(\textbf{y} - \mu) \sim N_4(0, I_4) \implies \textbf{z} = (\Sigma^{1/2})^{-1}(\textbf{y}-\mu)\implies (\Sigma^{1/2})\textbf{z} + \mu = \textbf{y}$.  
  
So we have $A = \Sigma^{1/2}$ and $b = \mu$.  
  
We can calulcate $\Sigma^{1/2}$ using spectral decomposition...

In [10]:
eigen(Sigma)
values <- eigen(Sigma)$values
vectors <- eigen(Sigma)$vectors
D_sqrt = matrix(rep(0,length(Sigma)), ncol = 4)
for (i in 1:4) {
    D_sqrt[i,i] = sqrt(values[i])
}
D_sqrt

Sigma_sqrt <- vectors %*% D_sqrt %*% t(vectors)
Sigma_sqrt

eigen() decomposition
$values
[1] 33.6683933 24.1538739  2.8096607  0.3680721

$vectors
           [,1]       [,2]       [,3]        [,4]
[1,] -0.5097713 -0.4314488  0.4748785  0.57312797
[2,] -0.3197622 -0.6544947 -0.1248813 -0.67364199
[3,]  0.1234259 -0.3902366 -0.7844396  0.46597851
[4,] -0.7890827  0.4829120 -0.3788795 -0.02438923


[,1]     [,2]     [,3]     [,4]     
[1,] 5.802447 0.000000 0.000000 0.0000000
[2,] 0.000000 4.914659 0.000000 0.0000000
[3,] 0.000000 0.000000 1.676204 0.0000000
[4,] 0.000000 0.000000 0.000000 0.6066895

[,1]          [,2]          [,3]          [,4]         
[1,]  3.000000e+00  2.000000e+00 -1.141621e-15  1.000000e+00
[2,]  2.000000e+00  3.000000e+00  1.000000e+00 -2.774183e-16
[3,] -1.226355e-15  1.000000e+00  2.000000e+00 -1.000000e+00
[4,]  1.000000e+00 -2.837441e-16 -1.000000e+00  5.000000e+00

Thus, we have 
$$A = \Sigma^{1/2} = \begin{pmatrix} 3 & 2 & 0 & 1 \\ 2 & 3 & 1 & 0 \\ 0 & 1 & 2 & -1 \\ 1 & 0 & -1 & 5 \end{pmatrix}$$
and 
$$ b = \mu = \begin{pmatrix} 1 \\ 3 \\ 5 \\ 6 \end{pmatrix} $$
## b)
We are given that $\textbf{y} \sim N_4(\mu, \Epsilon)$, therefore a random sample $\textbf{y}_1,..., \textbf{y}_n$ from the distribution of $\textbf{y}$ will also be multivariate normal with $\textbf{y}_1,..., \textbf{y}_n \sim N_4(\mu, \Sigma / n)$.
## c)
We can generate 100 sample mean vectors on size 55 like so...

In [11]:
library(MASS)
set.seed(1992)
samples <- t(replicate(100, colMeans(mvrnorm(55, mu, Sigma))))

y_bar <- colMeans(samples)
y_bar
cov(samples)

[1] 1.029341 3.001968 4.963894 6.037227

[,1]       [,2]        [,3]        [,4]       
[1,] 0.19213799  0.16754696  0.01474956  0.09220623
[2,] 0.16754696  0.21925164  0.09309206 -0.03771610
[3,] 0.01474956  0.09309206  0.11847257 -0.14837637
[4,] 0.09220623 -0.03771610 -0.14837637  0.44744428

Using the formula from part b), we would have.

In [12]:
y_bar_Sigma <- Sigma / 55
y_bar_Sigma

[,1]       [,2]       [,3]        [,4]       
[1,] 0.25454545 0.21818182  0.01818182  0.14545455
[2,] 0.21818182 0.25454545  0.09090909  0.01818182
[3,] 0.01818182 0.09090909  0.10909091 -0.12727273
[4,] 0.14545455 0.01818182 -0.12727273  0.49090909

The calculated sample mean vector lines up almost exactly, and the covariance matrix are similar to part b).